# Generated by Django 3.2 on 2021-08-26 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_reservationinfo'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='reservationinfo',
            unique_together={('reserved_date', 'hotel_room')},
        ),
    ]
