# Generated by Django 3.2 on 2021-09-04 01:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_alter_reservationinfo_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='reservationinfo',
            unique_together=set(),
        ),
    ]
