# Generated by Django 3.2 on 2021-09-08 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0007_alter_reservationinfo_hotel_room'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='reservationinfo',
            unique_together=set(),
        ),
    ]
