# Generated by Django 3.2 on 2021-09-08 18:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0008_alter_reservationinfo_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservationinfo',
            name='listing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reservation_info', to='listings.listing'),
        ),
    ]
